### ISSUE TITLE
Update for 1.0 release

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/compiler#3]
This code is out of date for the 1.0 release of the standard.

In https://github.com/open-contracting/compiler/commit/3bafaa1d46d1c7c808931e296197074805ded971 I made the changes  necessary for the code to run without exceptions -
there may be other out of date fields that do not cause exceptions.
Also, the "full" output is still out of date with the current spec, as
mentioned in the README.

**Comment by jpmckinney** [comment]
Is this a repository that we need to include in our upgrade workflow, or is it dead and can be archived? If it's not dead, then it should work with the latest schema.

**Comment by timgdavies** [comment]
My understanding is that this repo can also be archived.

I've not seen it used at all in the last two years.

**Comment by jpmckinney** [comment]
Closing this issue as 'wontfix' and archiving the repo.
